### ISSUE TITLE
Frequent build errors on Netlify

### ISSUE THREAD

**Issue by marcoSven** [styxlab/gatsby-theme-try-ghost#204] opened 2020-10-30 18:45 UTC
I experience intermittently build errors. They do not appear to be related to CMS content changes or code changes, it just randomly, unfortunately frequently, fails.

The following changes did not improve or worsen the fail rate - I think 
I removed netlify-plugin-gatsby-cache - [ #44](https://github.com/jlengstorf/netlify-plugin-gatsby-cache/issues/44#issue-719109938)
I removed gatsby-rehype-inline-images - #202 

Clearing the cache before a deploy is not helping in my opinion.

The error is always something like this
...
11:17:15 AM: success run static queries - 0.204s - 16/16 78.48/s
11:17:18 AM: error [object Object] ENOENT: no such file or directory, unlink '/opt/build/repo/public/static/c79ed69a45dfa3eb3fa94442cc61454a/photo-1499479387933-4567e710809c.jpg'
11:17:18 AM: 
11:17:18 AM: 
11:17:18 AM:   Error: ENOENT: no such file or directory, unlink '/opt/build/repo/public/stati  c/c79ed69a45dfa3eb3fa94442cc61454a/photo-1499479387933-4567e710809c.jpg'
11:17:18 AM: 
11:17:18 AM: not finished Generating image thumbnails - 13.367s
11:17:18 AM: not finished run page queries - 2.574s
...
11:17:18 AM: Failed during stage 'building site': Build script returned non-zero exit code: 2
11:17:18 AM: Finished saving boot dependencies
11:17:18 AM: Started saving go dependencies
11:17:18 AM: Finished saving go dependencies
11:17:18 AM: Build failed due to a user error: Build script returned non-zero exit code: 2
11:17:18 AM: Failing build: Failed to build site
11:17:19 AM: Finished processing build request in 47.137682029s

**Comment by marcoSven** [comment] 2020-10-30 18:50
here is another one 

11:47:09 AM: success run static queries - 0.106s - 16/16 150.38/s
11:47:13 AM: error [object Object] ENOENT: no such file or directory, unlink '/opt/build/repo/public/static/be02825633540f618f4010844e830d2f/photo-1541337326331-c1bd6156f6f6.jpg'
11:47:13 AM: 
11:47:13 AM: 
11:47:13 AM:   Error: ENOENT: no such file or directory, unlink '/opt/build/repo/public/stati  c/be02825633540f618f4010844e830d2f/photo-1541337326331-c1bd6156f6f6.jpg'
11:47:13 AM: 
11:47:13 AM: not finished Generating image thumbnails - 14.152s
11:47:13 AM: not finished run page queries - 3.623s
11:47:13 AM: (sharp:1364): GLib-CRITICAL **: 18:47:13.145: g_hash_table_lookup: assertion 'hash_table != NULL' failed
11:47:13 AM: (sharp:1364): GLib-CRITICAL **: 18:47:13.145: g_hash_table_lookup: assertion 'hash_table != NULL' failed
11:47:13 AM: (sharp:1364): GLib-CRITICAL **: 18:47:13.145: g_hash_table_lookup: assertion 'hash_table != NULL' failed
11:47:13 AM: (sharp:1364): GLib-CRITICAL **: 18:47:13.145: g_hash_table_lookup: assertion 'hash_table != NULL' failed
11:47:13 AM: (sharp:1364): GLib-CRITICAL **: 18:47:13.145: g_hash_table_insert_internal: assertion 'hash_table != NULL' failed
11:47:13 AM: (sharp:1364): GLib-CRITICAL **: 18:47:13.145: g_hash_table_lookup: assertion 'hash_table != NULL' failed
11:47:16 AM: bash: line 1:  1364 Segmentation fault      (core dumped) gatsby build --log-pages --verbose
11:47:16 AM: ​
11:47:16 AM: ┌─────────────────────────────┐
11:47:16 AM: │   "build.command" failed    │
11:47:16 AM: └─────────────────────────────┘
11:47:16 AM: ​

**Comment by styxlab** [comment] 2020-10-30 21:32
The sharp errors look scary but can be ignored (there is an async issue in the gatsby-plugin-sharp plugin, but the images are still generated). The other build errors, however, should not happen and I am surprised to see those given that I also deploy on Netlify without problems. Could you please first test, if you also see those errors when building locally?

**Comment by marcoSven** [comment] 2020-10-30 23:25
Funny I just had the first time the same error on my local. 

1. yarn clean
2. yarn build

I looked for the file in demo/public/static and it did exist. I ran yarn build and everything was fine 🙃. Any advice on what to look for? I am just starting out with Gatsby,  

wondering if 

- this is related to the async issue in the gatsby-plugin-sharp, though I do not see the error every time the build fails. 
- memory issue 

> how many images are you processing?

Not many less than 15 pages and 1-3 images each.

**Comment by marcoSven** [comment] 2020-10-31 04:42
So I signed up for Gatsby, I made 3 deploys so far, and they always succeded in Gatsby but failed on Netlify. 

I experienced the issues once more on my local, so I am not 100% confident that building on Gatsby solves my issue.

**Comment by styxlab** [comment] 2020-10-31 09:33
I also build on Gatsby Cloud and not directly on Netlify, but I am also not seeing the issue locally. Could you please provide your repo with (temporary) API keys, so I can test your site locally on my machine? This is most likely either a problem with the used Gatsby version or related to your (local/Netlify) build system.

**Comment by marcoSven** [comment] 2020-10-31 13:26
> I also build on Gatsby Cloud and not directly on Netlify

Not sure if I like that dependency 😄 but it works flawlessly so far. I am currently building simultaneously on both and Netlify always fails. I have removed the lock file btw and the build installs the packages with npm. I use yarn locally.

> remove your public folder before building?
remove node_modules + yarn.lock, then issue yarn to recreate?

I tried a lot of things replicated the same steps after a fail, but since the build time takes a while this is a painful time suck.
So far I have not been able to consistently reproduce the issue on my local. The public folder is removed when you run clean, no?

>  This is most likely either a problem with the used Gatsby version or related to your (local/Netlify) build system.

Local - Gatsby CLI version: 2.12.107  node v12.19.0
Netlify - gatsby-cli@2.12.113 node v12.18.0

Gatsby - Gatsby CLI version: 2.12.113 Node  v12.19.0

I still think it's related to image processing and running out of memory,  and considering the lighthouse results mentioned in #203 images not correctly sized etc maybe improvements will help with this issue.

> Error: ENOENT: no such file or directory, chmod '/opt/build/repo/public/static

Thoughts on how I can trace the error? All I was able to confirm is that the file does exist at least after the failed build, not sure where the error is thrown and how to debug.

**Comment by styxlab** [comment] 2020-11-01 17:10
I'd be surprised if the error is related to image processing and running out of memory. You can turn off Gatsby image processing entirely by:

- removing `gatsby-rehype-inline-images` (for inline images)
- setting the flag `gatsbyImages` to `false` in `mediaConfig.js` (for feature images).

This could be a first step in trying to localize the issue.

**Comment by marcoSven** [comment] 2020-11-01 21:44
I already removed gatsby-rehype-inline-images and I will give removing the feature images a try

**Comment by marcoSven** [comment] 2020-11-02 00:09
While I looked at #202 I cloned this repository 
changed content API settings in /dev/gatsby-theme-try-ghost/packages/gatsby-theme-try-ghost/src/utils/.ghost.json

installed packages with yarn and ran yarn build

and got this error Error: ENOENT: no such file or directory, chmod '/dev/gatsby-theme-try-ghost/demo/public/static/d5aa518ea784e1b659  b6bf9a69bd6f76/site-meta.png'

yarn build right after no error

**Comment by styxlab** [comment] 2020-11-02 07:46
> and got this error Error: ENOENT: no such file or directory, chmod '/dev/gatsby-theme-try-ghost/demo/public/static/d5aa518ea784e1b659 b6bf9a69bd6f76/site-meta.png'

Sounds like a duplicate of #188 if you are building on macOS. I think this error is different from the ones showing the `unlink` error message, although they could have the same root cause. My hunch is that Gatsby has a problem with with cache invalidation. If we can fully replicate the issues we can report them upstream. Before, I will update the project to the latest gatsby version, so we don't report intermittent problems.

**Comment by marcoSven** [comment] 2020-11-14 08:06
> If we can fully replicate the issues we can report them upstream

Try 
https://gitpod.io/#snapshot/142e3a5b-3c8c-46c5-ad99-6fbaa85836e7

run yarn develop

**Comment by styxlab** [comment] 2020-11-14 20:32
No errors - neither with yarn develop nor yarn build:
```
gitpod /workspace/gatsby-starter-try-ghost $ yarn develop
yarn run v1.22.10
$ gatsby develop
success open and validate gatsby-configs - 0.317s
success load plugins - 1.045s
success onPreInit - 0.077s
success initialize cache - 0.006s
success copy gatsby files - 0.078s
success onPreBootstrap - 0.023s
success createSchemaCustomization - 0.026s
success Checking for changed pages - 0.001s
success source and transform nodes - 0.383s
success building schema - 1.137s
info Total nodes: 123, SitePage nodes: 17 (use --verbose for breakdown)
success createPages - 0.428s
success Checking for changed pages - 0.001s
success createPagesStatefully - 0.148s
success update schema - 0.059s
success write out redirect data - 0.002s
success onPostBootstrap - 0.002s
info bootstrap finished - 7.207s
success onPreExtractQueries - 0.001s
success extract queries from components - 1.212s
warning The GraphQL query in the non-page component "/workspace/gatsby-starter-try-ghost/node_modules/gatsby-theme-try-ghost/src/templates/page.js" will not be run.
Exported queries are only executed for Page components. It's possible you're
trying to create pages in your gatsby-node.js and that's failing for some
reason.

If the failing component(s) is a regular component and not intended to be a page
component, you generally want to use a <StaticQuery> (https://gatsbyjs.org/docs/static-query)
instead of exporting a page query.

If you're more experienced with GraphQL, you can also export GraphQL
fragments from components and compose the fragments in the Page component
query and pass data down into the child component — https://graphql.org/learn/queries/#fragments
success write out requires - 0.052s
success run page queries - 0.042s - 1/1 23.83/s
⠀
You can now view gatsby-starter-try-ghost in the browser.
⠀
  http://localhost:8000/
⠀
View GraphiQL, an in-browser IDE, to explore your site's data and schema
⠀
  http://localhost:8000/___graphql
⠀
Note that the development build is not optimized.
To create a production build, use gatsby build
⠀
success Building development bundle - 7.757s
```

**Comment by styxlab** [comment] 2020-11-23 09:23
Fun fact: this error tells you something about the speed of your file-system. The faster your file writes the less likely you run into this error.

**Comment by styxlab** [comment] 2020-11-23 19:17
@marcoSven: Could you please verify that the reported build errors are fixed?

**Comment by marcoSven** [comment] 2020-11-24 05:04
I had a hunch something hardware is related to this intermittent issue. Tells you something about Netlify vs Gatsby Cloud - kind of annoyed this was frequently happening on my Mac ;) 

Looks like it is fixed!!! 🎉

**Comment by styxlab** [comment] 2020-11-24 08:34
Perfect... and thanks for bringing this up. Both this project *and* official Gatsby benefited from it.

**Closed by styxlab** 2020-11-24 08:34 UTC
