### ISSUE TITLE
Inline images in blog post not sourced from /static but from original Ghost website

### ISSUE THREAD

**Issue by jpalpant** [styxlab/gatsby-theme-try-ghost#47] opened 2020-04-27 00:38 UTC
Just learning to use this project, and so far I love it! My site is quite a bit faster and handles load tests better than the original Ghost site did, along with many other improvements. Thanks for the awesome work!

I run Ghost via a Docker container, which is available on the internet at one URL ([ghost.justin.palpant.us](https://ghost.justin.palpant.us/)). That ghost blog is marked as Private. I use that URL as the target in my .ghost.json, and then build another Docker image this Gatsby starter repo. I then run the Gatsby Docker image on another URL, [justin.palpant.us](https://justin.palpant.us/)

I noticed, however, that when I put an image into my Ghost blog, inline, using the Image or Gallery tools, those images aren't being served from the statically built site, but instead still use the original Ghost URLs, ghost.justin.palpant.us/content/images/...
 
<img width="357" alt="Screenshot 2020-04-26 17 28 35" src="https://user-images.githubusercontent.com/9629191/80324011-603a9780-87e3-11ea-8731-ddc426ce762a.png">

I'd definitely prefer not to need the Ghost blog to be up at all and to have 100% of the content served from the static Gatsby site. Post header images do work this way, with the header image being stored in the Gatsby image and served from a relative static path from the Gatsby site.

An example of images being served from the original Ghost can be seen in [a post I just made about messing around with my GPUs](https://justin.palpant.us/monitor-and-maximize-nvidia-gpu-performance-on-linux/):

<img width="1341" alt="Screenshot 2020-04-26 17 34 58" src="https://user-images.githubusercontent.com/9629191/80324173-59f8eb00-87e4-11ea-9173-b730b53657d6.png">

Whereas post header images can be served from /static:
<img width="1340" alt="Screenshot 2020-04-26 17 36 14" src="https://user-images.githubusercontent.com/9629191/80324202-83197b80-87e4-11ea-97a5-f88f0de4a0a8.png">

Now, I have to admit, I have only the vaguest idea of how this Gatsby site generator works - aside from the fact that `gatsby build` somehow downloads the content of my Ghost blog using the Content API, I'm lost. But I thought I'd check - is this expected behavior, that Image and Gallery sections will be sourced with original full URLs?

Happy to help with any additional information or contributions if I can!

**Comment by styxlab** [comment] 2020-04-27 08:01
@jpalpant Thanks a lot for the feedback and for using this project!

The short answer to your question is: Yes this is expected behaviour. The image insourcing is currently only done for feature images. 

The reason for not having incorporated inline images yet:

1. It's more complicated compared to feature images (you first have to extract all image paths in the body text, store those paths in the GraphQL database, query and insert them in the right place, make sure the caching is still working, etc.)

2. It will prolong Gatsby build times. For small projects this is not a problem, but as build time *is* and issue with any Gatsby project, I'm a bit cautious on this point. With incremental build emerging, maybe this is just the right time to implement this feature?!

3. I already created a package directory for this [feature](https://github.com/styxlab/gatsby-theme-try-ghost/tree/master/packages/gatsby-rehype-remote-images), but didn't get around implementing it.

I definitely support implementing such a feature (as a rehype-* plugin). I see that you have a lot of development experience. [Get in contact](https://atmolabs.org/contact/) with me, if you want to collaborate on creating this feature.

**Comment by jpalpant** [comment] 2020-04-27 20:22
Thanks! Would love to collaborate on this if I'm able, I dropped a message via that email though I think there may be an issue with the submission, so please shoot me an email where I can reach you if it didn't go through - my email is in my GH profile.

**Comment by erm87** [comment] 2020-05-09 19:31
Hey guys, just wanted to show my support for this project! I'm not a fluent developer, just a PM that is obsessed with efficiency. In my journey to build the most optimized and fast blog site I've landed here 🙂

I have tried the [gatsby-plugin-ghost-images](https://www.gatsbyjs.org/packages/gatsby-plugin-ghost-images/) plugin which is supposed to solve for putting images within post content through the gatsby-image and sharp processors. However, I got stuck on the query and accessing it within react.

Perhaps this could be leveraged with this theme by a more skilled developer.

Again, really love this project -- I've tried a bunch of combinations of Ghost, Ghost+Cloudinary, Ghost w/ Gatsby, etc, and this one has gotten the closest to perfect performance. The last little mole to hit is optimizing all the in-content images somehow 💪

**Comment by tobimori** [comment] 2020-05-09 19:48
gatsby-plugin-ghost-images currently only sources cover/profile/feature images. not post content.

**Comment by erm87** [comment] 2020-05-09 19:55
@tobimori ah thanks for the confirmation! Actually, just resolved an issue with my query and saw it was only grabbing feature_image.. oh well!

**Comment by styxlab** [comment] 2020-06-08 12:23
The development of this plugin has been stalled due to missing developer capacity. If you want to sponsor development of this feature, please get in contact with me.

**Comment by styxlab** [comment] 2020-06-22 10:36
Reopened. This is a long standing enhancement that will be solved soon!

**Comment by styxlab** [comment] 2020-06-23 18:38
solved with PR #131

**Closed by styxlab** 2020-06-23 18:38 UTC
Labels: enhancement
