### ISSUE TITLE
Internal ghost tag used for 404.html 

### ISSUE THREAD

**Issue by marcoSven** [styxlab/gatsby-theme-try-ghost#198] opened 2020-10-22 13:20 UTC
To replicate create an internal tag and tag a post. clean & develop. 
Result 404 page is created from /pages/404 and 404.html is created with templates/tag.

Ghost content API returns internal tags with a 404 URL, 404 pages from ghost cms should be ignored.

**Comment by styxlab** [comment] 2020-10-23 22:54
Thanks for reporting. Generally it is correct that internal tags are coming through, because they can be used for routing purposes. They should not show up on the generated sites, but if you manually point to e.g. /tag/#internal-tag you should get a 404 page.

Could you please contrast the current behavior of this package with the way original Ghost behaves? Do you have the issue reproduced, so I can clone that repo?

**Comment by marcoSven** [comment] 2020-10-26 18:43
> Thanks for reporting. Generally, it is correct that internal tags are coming through, because they can be used for routing

Yes that is great

> /tag/#internal-tag 

The path would be /tag/hash-internal-tag and yes it goes to 404 that is not my problem.

My problem is that my 404.index is created with the content of the internal-tag page.

https://tryghost404.netlify.app/this-page-should-return-404

like the source https://ghostwriter.bettinalimaco.com/this-page-should-return-404/

Here is the forked version of this repository that is deployed to Netlify - https://github.com/marcoSven/gatsby-theme-try-ghost

**Comment by styxlab** [comment] 2020-10-27 10:29
Thanks for the clarification. I am now able to reproduce the issue internally. Will be fixed in next release.

**Closed** 2020-10-27 13:16 UTC
Labels: bug
