### ISSUE TITLE
Error: Cannot find module '@mdx-js/mdx'

### ISSUE THREAD

**Issue by pascalandy** [styxlab/gatsby-theme-try-ghost#186] opened 2020-09-28 22:54 UTC
Hi, 

I'm super committed to move to a jamstack using Ghost, Gatsby and TailwindCSS. I'm following your tutorial https://www.jamify.org/2020/07/15/running-a-professional-blog-for-free/ and https://www.jamify.org/2020/05/19/getting-started-with-jamify/ and I can't get started yet.

### ghost

looks good

```
ghost-local │ /Volumes/960G/_pascalandy/11_FirePress/Github/github_pascalandy/_ghost_local_dev │ 3.34.1  │ running (development) │ http://localhost:2368/ │ 2368 │ local
```

### node version

looks good

```
node --version
v12.13.0
```

### yarn

yarn compile normally

```
➜  jamify-starter git:(master) ✗ yarn
yarn install v1.22.4
[1/4] 🔍  Resolving packages...
success Already up-to-date.
✨  Done in 0.59s.
```

### error

```
➜  jamify-starter git:(master) ✗ yarn develop
yarn run v1.22.4
$ gatsby develop
internal/modules/cjs/loader.js:797
    throw err;
    ^

Error: Cannot find module '@mdx-js/mdx'
Require stack:
- /Volumes/960G/_pascalandy/11_FirePress/Github/github_pascalandy/user_styxlab/jamify-starter/node_modules/gatsby-recipes/dist/transform-recipe-mdx.js
- /Volumes/960G/_pascalandy/11_FirePress/Github/github_pascalandy/user_styxlab/jamify-starter/node_modules/gatsby-recipes/dist/renderer/index.js
- /Volumes/960G/_pascalandy/11_FirePress/Github/github_pascalandy/user_styxlab/jamify-starter/node_modules/gatsby-recipes/dist/validate-steps.js
- /Volumes/960G/_pascalandy/11_FirePress/Github/github_pascalandy/user_styxlab/jamify-starter/node_modules/gatsby-recipes/dist/recipe-machine/index.js
- /Volumes/960G/_pascalandy/11_FirePress/Github/github_pascalandy/user_styxlab/jamify-starter/node_modules/gatsby-recipes/dist/graphql-server/server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Volumes/960G/_pascalandy/11_FirePress/Github/github_pascalandy/user_styxlab/jamify-starter/node_modules/gatsby-recipes/dist/transform-recipe-mdx.js:12:35)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Volumes/960G/_pascalandy/11_FirePress/Github/github_pascalandy/user_styxlab/jamify-starter/node_modules/gatsby-recipes/dist/transform-recipe-mdx.js',
    '/Volumes/960G/_pascalandy/11_FirePress/Github/github_pascalandy/user_styxlab/jamify-starter/node_modules/gatsby-recipes/dist/renderer/index.js',
    '/Volumes/960G/_pascalandy/11_FirePress/Github/github_pascalandy/user_styxlab/jamify-starter/node_modules/gatsby-recipes/dist/validate-steps.js',
    '/Volumes/960G/_pascalandy/11_FirePress/Github/github_pascalandy/user_styxlab/jamify-starter/node_modules/gatsby-recipes/dist/recipe-machine/index.js',
    '/Volumes/960G/_pascalandy/11_FirePress/Github/github_pascalandy/user_styxlab/jamify-starter/node_modules/gatsby-recipes/dist/graphql-server/server.js'
  ]
}

success open and validate gatsby-configs - 0.208s
⠋ load plugins
dyld: lazy symbol binding failed: Symbol not found: _g_once_impl
  Referenced from: /Volumes/960G/_pascalandy/11_FirePress/Github/github_pascalandy/user_styxlab/jamify-starter/node_modules/gatsby-rehype-inline-images/node_modules/sharp/build/Release/sharp.node
  Expected in: /Volumes/960G/_pascalandy/11_FirePress/Github/github_pascalandy/user_styxlab/jamify-starter/node_modules/sharp/build/Release/../../vendor/lib/libvips.42.dylib

dyld: Symbol not found: _g_once_impl
  Referenced from: /Volumes/960G/_pascalandy/11_FirePress/Github/github_pascalandy/user_styxlab/jamify-starter/node_modules/gatsby-rehype-inline-images/node_modules/sharp/build/Release/sharp.node
  Expected in: /Volumes/960G/_pascalandy/11_FirePress/Github/github_pascalandy/user_styxlab/jamify-starter/node_modules/sharp/build/Release/../../vendor/lib/libvips.42.dylib

error Command failed with signal "SIGKILL".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by styxlab** [comment] 2020-09-29 06:54
Hi Pascal! Welcome to this project, this is an awesome stack you are moving to 😊

The module that the compiler complains about is not part of 'gatsby-theme-try-ghost', so I am wandering what customizations you made to this project.

Is there a repo that I can clone and test myself?

**Comment by styxlab** [comment] 2020-09-29 09:09
After updating the `gatsby` dependencies, the issue is fixed. Please clear your caches (or start from scratch). I have updated all packages on `npm` so you should be good to go.

**Comment by pascalandy** [comment] 2020-09-29 11:11
Will test again (now on the go!!)

**Comment by pascalandy** [comment] 2020-09-30 15:30
Got an error. It's not the same but it's close:

```
➜  jamify-starter git:(master) ✗ yarn develop
yarn run v1.22.4
$ gatsby develop
success open and validate gatsby-configs - 0.842s
⠋ load plugins
dyld: lazy symbol binding failed: Symbol not found: _g_once_impl
  Referenced from: /Users/andy_lap/Documents/github/pascalandy/jamify-starter/node_modules/gatsby-rehype-inline-images/node_modules/sharp/build/Release/sharp.node
  Expected in: /Users/andy_lap/Documents/github/pascalandy/jamify-starter/node_modules/sharp/build/Release/../../vendor/lib/libvips.42.dylib

dyld: Symbol not found: _g_once_impl
  Referenced from: /Users/andy_lap/Documents/github/pascalandy/jamify-starter/node_modules/gatsby-rehype-inline-images/node_modules/sharp/build/Release/sharp.node
  Expected in: /Users/andy_lap/Documents/github/pascalandy/jamify-starter/node_modules/sharp/build/Release/../../vendor/lib/libvips.42.dylib

error Command failed with signal "SIGKILL".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by styxlab** [comment] 2020-09-30 18:26
Just clearing the cache is not sufficient. You can try:

1. `git pull` (to get the latest dependency changes that)
2. `rm -rf node_modules`
3. `rm -rf yarn.lock`
4. `yarn` (this recreates all modules and yarn.lock)
5. `yarn cache clean`
6. `yarn develop`

If that doesn't do the trick, I suggest you start from scratch (cloning the repo again, following the instructions in the tutorial). That's the most bullet proof method.

**Comment by pascalandy** [comment] 2020-09-30 19:55
I started from scratch (and another computer) this morning. 

I also followed your steps to cleanup and I have the same error:

```
jamify-starter git:(master) ✗ yarn develop
yarn run v1.22.5
$ gatsby develop
success open and validate gatsby-configs - 0.843s
⠋ load plugins
dyld: lazy symbol binding failed: Symbol not found: _g_once_impl
  Referenced from: /Users/andy_lap/Documents/github/pascalandy/jamify-starter/node_modules/gatsby-rehype-inline-images/node_modules/sharp/build/Release/sharp.node
  Expected in: /Users/andy_lap/Documents/github/pascalandy/jamify-starter/node_modules/sharp/build/Release/../../vendor/lib/libvips.42.dylib

dyld: Symbol not found: _g_once_impl
  Referenced from: /Users/andy_lap/Documents/github/pascalandy/jamify-starter/node_modules/gatsby-rehype-inline-images/node_modules/sharp/build/Release/sharp.node
  Expected in: /Users/andy_lap/Documents/github/pascalandy/jamify-starter/node_modules/sharp/build/Release/../../vendor/lib/libvips.42.dylib

error Command failed with signal "SIGKILL".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
➜  jamify-starter git:(master) ✗
```

**Comment by styxlab** [comment] 2020-09-30 20:39
Are you running macOS? If so, do you have the possibility to test on another OS?

**Comment by pascalandy** [comment] 2020-09-30 22:15
Yes I'm on MacOS 10.15.6 Mojave. No other OS around.

**Comment by styxlab** [comment] 2020-10-01 08:50
Am not able to reproduce the issue, but currently do not have macOS available for testing.
As the error occurs in `gatsby-rehype-inline-images`, could you please remove that package?

1. Remove in `gatsby-config.js`
2. yarn remove `gatsby-rehype-inline-images` (or delete in package.json)
3. yarn
4. yarn clean
5. yarn develop

I'm sorry for the trouble, this should be really easy and trouble free.

**Comment by styxlab** [comment] 2020-10-01 10:28
Here is my  test on macOS Catalina 10.15.7:

```
node -v 
v12.18.4

yarn -v
1.22.5

gatsby -v
Gatsby CLI version 2.12.100
```
The most basic test is to clone the _Jamify Starter_ and just build the project without any modifications:
```
git clone https://github.com/styxlab/gatsby-starter-try-ghost.git jamify-starter
cd jamify-starter
yarn
yarn develop
```
You'll see a lot of logs(*), but you should be able to access the site under `http://localhost:8000` after the build finishes. Can you please repeat these steps from scratch and report back?

(*) Under macOS I see a couple of copy errors that I haven't seen before. Those can be ignored (files are still copied correctly), but I will investigate those further.

**Comment by pascalandy** [comment] 2020-10-01 12:53
Hi,

I was able to to make it work using theses steps:

```
Remove in gatsby-config.js
yarn remove gatsby-rehype-inline-images (or delete in package.json)
yarn
yarn clean
yarn develop
```

**Comment by pascalandy** [comment] 2020-10-01 12:54
But when I do yarn build, I got this error 

```
(sharp:17510): GLib-CRITICAL **: 08:51:41.838: g_hash_table_lookup: assertion 'hash_table != NULL' failed
✨  Done in 55.32s.
```


```
yarn develop

➜  jamify-starter git:(master) ✗ yarn build
yarn run v1.22.5
$ gatsby build --log-pages
success open and validate gatsby-configs - 0.744s
success load plugins - 2.223s
success onPreInit - 0.074s
success delete html and css files from previous builds - 0.008s
success initialize cache - 0.006s
success copy gatsby files - 0.196s
success onPreBootstrap - 0.038s
success createSchemaCustomization - 0.068s
success Checking for changed pages - 0.002s
success source and transform nodes - 0.360s
success building schema - 0.636s
info Total nodes: 130, SitePage nodes: 19 (use --verbose for breakdown)
success createPages - 0.878s
success Checking for changed pages - 0.003s
success createPagesStatefully - 0.107s
success Cleaning up stale page-data - 0.016s
success update schema - 0.059s
success onPreExtractQueries - 0.005s
success extract queries from components - 0.791s
warn The GraphQL query in the non-page component
Exported queries are only executed for Page components. It's possible you're
trying to create pages in your gatsby-node.js and that's failing for some
reason.

If the failing component(s) is a regular component and not intended to be a page
component, you generally want to use a <StaticQuery> (https://gatsbyjs.org/docs/static-query)
instead of exporting a page query.

If you're more experienced with GraphQL, you can also export GraphQL
fragments from components and compose the fragments in the Page component
query and pass data down into the child component — https://graphql.org/learn/queries/#fragments
success write out redirect data - 0.004s
success onPostBootstrap - 0.004s
info bootstrap finished - 14.087s
success run static queries - 0.110s - 6/6 54.43/s
success run page queries - 1.632s - 20/20 12.26/s
success write out requires - 0.008s
success Building production JavaScript and CSS bundles - 31.917s
success Rewriting compilation hashes - 0.030s
success Building static HTML for pages - 6.475s - 20/20 3.09/s
success Generating image thumbnails - 42.321s - 22/22 0.52/s
success onPostBuild - 0.222s
info Done building in 54.824834902 sec

(sharp:17510): GLib-CRITICAL **: 08:51:41.838: g_hash_table_lookup: assertion 'hash_table != NULL' failed
✨  Done in 55.32s.

```

**Comment by styxlab** [comment] 2020-10-01 13:38
Those glib errors can be ignored, see #174.

So, the original issue has been confined to gatsby-rehype-inline-images on macOS. I will see if I can manage to reproduce it on my systems.

**Comment by styxlab** [comment] 2020-10-01 20:57
Reproduced the issue with `gatsby-rehype-inline-images` on macOS...

**Comment by styxlab** [comment] 2020-10-02 07:41
As the original issue has been solved, I close this in favour of #188 and #190.

**Comment by styxlab** [comment] 2020-10-02 09:20
@pascalandy: Issue #190 is fixed now. Could you please verify on your end?

**Comment by pascalandy** [comment] 2020-10-02 18:29
Will do, on the go ATM

**Comment by pascalandy** [comment] 2020-10-03 14:50
I confirm it works now.

**Comment by pascalandy** [comment] 2020-10-03 14:52
Things to improve IMHO:

- In the guide https://www.jamify.org/2020/07/15/running-a-professional-blog-for-free/ you should mention that we need to do `yarn develop` under /demo.
- It would be nice to understand why there is a `/demo` sub-dir actually.
- `yarn build` should be mentioned as well.
- then continue with the netlify thing.

Cheers!

**Comment by styxlab** [comment] 2020-10-03 15:55
> I confirm it works now.

Perfect, thanks for reporting back!

**Comment by styxlab** [comment] 2020-10-03 16:02
> Things to improve IMHO:
> 
> 
> 
> - In the guide https://www.jamify.org/2020/07/15/running-a-professional-blog-for-free/ you should mention that we need to do `yarn develop` under /demo.
> 
> - It would be nice to understand why there is a `/demo` sub-dir actually.
> 
> - `yarn build` should be mentioned as well.
> 
> - then continue with the netlify thing.
> 
> 
> 
> Cheers!
> 
> 

Thanks again for your feedback, I really value your input. 

In this case, however, I think you didn't follow the guide correctly. There is no 'demo' folder in 'gatsby-starter-try-Ghost'!

I suspect you mistakenly use 'gatsby-theme-try-Ghost'. The theme is the dev project from which the starter is derived, but it should not be used by by the end-users.

**Comment by pascalandy** [comment] 2020-10-03 16:08
Oh yes, you're right :-p

> I suspect you mistakenly use 'gatsby-theme-try-Ghost'. The theme is the dev project from which the starter is derived, but it should not be used by by the end-users.

**Closed** 2020-10-05 15:03 UTC
Labels: bug
