### ISSUE TITLE
Deploy to Vercel button doesn't work.

### ISSUE THREAD

**Issue by DevelopingUK** [styxlab/gatsby-theme-try-ghost#263] opened 2021-04-13 17:21 UTC
The project fails to build, throwing GraphQL and URL errors.

**Comment by styxlab** [comment] 2021-04-13 17:59
I just tested the Vercel button and the [site is created](https://gatsby-test-blond.vercel.app/). There are some warning and some depreciation errors during the build process, but the project does not fail. I will try to fix these warnings in the next released, but I do not seem to be able to reproduce a failing build. Did you change environment variables or make any other customizations?

**Comment by DevelopingUK** [comment] 2021-04-13 18:05
Okay, it worked the first time now, thanks.

The only difference before was that I added ENV variables when deploying, this time I left them out and will add them manually after.

You're a hero for creating this version for Ghost/Gatsby!

thanks.

(Ps - may need to drop in for some more help)

**Comment by DevelopingUK** [comment] 2021-04-13 18:32
I think I spoke too soon...

I'm getting these errors every time I add my ENV variables on Vercel.

I tried to add them inside Vercel and even outside in a .ghost.JSON file separately.

Keep running into this error.


20:29:29.905 | error There was an error in your GraphQL query:
-- | --
20:29:29.906 | The "url" argument must be of type string. Received undefined
20:29:29.906 | 37 \|   url
20:29:29.906 | 38 \|   canonical_url
20:29:29.906 | 39 \|   uuid
20:29:29.907 | 40 \|   page
20:29:29.907 | 41 \|   codeinjection_foot
20:29:29.907 | 42 \|   codeinjection_head
20:29:29.907 | 43 \|   codeinjection_styles
20:29:29.907 | 44 \|   comment_id
20:29:29.907 | 45 \|   reading_time
20:29:29.908 | 46 \|   childHtmlRehype {
20:29:29.908 | > 47 \|     html
20:29:29.908 | \|     ^
20:29:29.908 | 48 \|     htmlAst
20:29:29.908 | 49 \|     tableOfContents
20:29:29.908 | 50 \|   }
20:29:29.908 | 51 \|   featureImageSharp {
20:29:29.909 | 52 \|     base
20:29:29.909 | 53 \|     publicURL
20:29:29.909 | 54 \|     imageMeta {
20:29:29.909 | 55 \|       width
20:29:29.909 | 56 \|       height
20:29:29.909 | 57 \|     }
20:29:29.910 | File path: /vercel/workpath0/node_modules/gatsby-theme-try-ghost/src/templates/page.js
20:29:29.910 | Url path: /privacy-policy/
20:29:29.910 | Plugin: none
20:29:29.946 |  
20:29:29.946 | Error: TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type st  ring. Received undefined
20:29:29.947 |  
20:29:29.947 | - validators.js:124 validateString
20:29:29.947 | internal/validators.js:124:11
20:29:29.947 |  
20:29:29.947 | - gatsby-node.js:19
20:29:29.947 | [workpath0]/[gatsby-rehype-ghost-links]/gatsby-node.js:19:22
20:29:29.947 |  
20:29:29.948 | - index.js:27 overload
20:29:29.948 | [workpath0]/[unist-util-visit]/index.js:27:12
20:29:29.948 |  
20:29:29.948 | - index.js:56 node (element<a>)
20:29:29.948 | [workpath0]/[unist-util-visit-parents]/index.js:56:27
20:29:29.948 |  
20:29:29.948 | - index.js:67 node (element<p>)
20:29:29.948 | [workpath0]/[unist-util-visit-parents]/index.js:67:75
20:29:29.948 |  
20:29:29.948 | - index.js:67 node (root)
20:29:29.949 | [workpath0]/[unist-util-visit-parents]/index.js:67:75
20:29:29.949 |  
20:29:29.949 | - index.js:29 visitParents
20:29:29.949 | [workpath0]/[unist-util-visit-parents]/index.js:29:26
20:29:29.949 |  
20:29:29.949 | - index.js:22 visit
20:29:29.949 | [workpath0]/[unist-util-visit]/index.js:22:3
20:29:29.949 |  
20:29:29.949 | - gatsby-node.js:16 module.exports
20:29:29.949 | [workpath0]/[gatsby-rehype-ghost-links]/gatsby-node.js:16:3
20:29:29.950 |  
20:29:29.950 | - extend-node-type.js:149
20:29:29.950 | [workpath0]/[gatsby-transformer-rehype]/extend-node-type.js:149:18
20:29:29.950 |  
20:29:29.950 | - extend-node-type.js:16 Function.Promise.each
20:29:29.950 | [workpath0]/[gatsby-transformer-rehype]/extend-node-type.js:16:11
20:29:29.950 |  
20:29:29.950 | - extend-node-type.js:142 processHtmlAst
20:29:29.950 | [workpath0]/[gatsby-transformer-rehype]/extend-node-type.js:142:21
20:29:29.950 |  
20:29:29.950 | - task_queues.js:58 runNextTicks
20:29:29.951 | internal/process/task_queues.js:58:5
20:29:29.951 |  
20:29:29.951 | - timers.js:434 processImmediate
20:29:29.951 | internal/timers.js:434:9
20:29:29.951 |  
20:29:29.951 |  
20:29:29.951 | error There was an error in your GraphQL query:
20:29:29.951 | The "url" argument must be of type string. Received undefined
20:29:29.952 | 38 \|   canonical_url
20:29:29.952 | 39 \|   uuid
20:29:29.952 | 40 \|   page
20:29:29.952 | 41 \|   codeinjection_foot
20:29:29.952 | 42 \|   codeinjection_head
20:29:29.952 | 43 \|   codeinjection_styles
20:29:29.952 | 44 \|   comment_id
20:29:29.952 | 45 \|   reading_time
20:29:29.952 | 46 \|   childHtmlRehype {
20:29:29.952 | 47 \|     html
20:29:29.953 | > 48 \|     htmlAst
20:29:29.953 | \|     ^
20:29:29.953 | 49 \|     tableOfContents
20:29:29.953 | 50 \|   }
20:29:29.953 | 51 \|   featureImageSharp {
20:29:29.953 | 52 \|     base
20:29:29.953 | 53 \|     publicURL
20:29:29.953 | 54 \|     imageMeta {
20:29:29.953 | 55 \|       width
20:29:29.953 | 56 \|       height
20:29:29.953 | 57 \|     }
20:29:29.953 | 58 \|     childImageSharp {
20:29:29.954 | File path: /vercel/workpath0/node_modules/gatsby-theme-try-ghost/src/templates/page.js
20:29:29.954 | Url path: /privacy-policy/
20:29:29.954 | Plugin: none
20:29:29.991 |  
20:29:29.991 | Error: TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type st  ring. Received undefined
20:29:29.991 |  
20:29:29.991 | - validators.js:124 validateString
20:29:29.991 | internal/validators.js:124:11
20:29:29.991 |  
20:29:29.991 | - gatsby-node.js:19
20:29:29.992 | [workpath0]/[gatsby-rehype-ghost-links]/gatsby-node.js:19:22
20:29:29.992 |  
20:29:29.992 | - index.js:27 overload
20:29:29.992 | [workpath0]/[unist-util-visit]/index.js:27:12
20:29:29.992 |  
20:29:29.992 | - index.js:56 node (element<a>)
20:29:29.992 | [workpath0]/[unist-util-visit-parents]/index.js:56:27
20:29:29.992 |  
20:29:29.992 | - index.js:67 node (element<p>)
20:29:29.992 | [workpath0]/[unist-util-visit-parents]/index.js:67:75
20:29:29.993 |  
20:29:29.993 | - index.js:67 node (root)
20:29:29.993 | [workpath0]/[unist-util-visit-parents]/index.js:67:75
20:29:29.993 |  
20:29:29.993 | - index.js:29 visitParents
20:29:29.993 | [workpath0]/[unist-util-visit-parents]/index.js:29:26
20:29:29.993 |  
20:29:29.993 | - index.js:22 visit
20:29:29.993 | [workpath0]/[unist-util-visit]/index.js:22:3
20:29:29.993 |  
20:29:29.994 | - gatsby-node.js:16 module.exports
20:29:29.994 | [workpath0]/[gatsby-rehype-ghost-links]/gatsby-node.js:16:3
20:29:29.994 |  
20:29:29.994 | - extend-node-type.js:149
20:29:29.994 | [workpath0]/[gatsby-transformer-rehype]/extend-node-type.js:149:18
20:29:29.994 |  
20:29:29.994 | - extend-node-type.js:16 Function.Promise.each
20:29:29.994 | [workpath0]/[gatsby-transformer-rehype]/extend-node-type.js:16:11
20:29:29.994 |  
20:29:29.994 | - extend-node-type.js:142 processHtmlAst
20:29:29.995 | [workpath0]/[gatsby-transformer-rehype]/extend-node-type.js:142:21
20:29:29.995 |  
20:29:29.995 | - task_queues.js:58 runNextTicks
20:29:29.995 | internal/process/task_queues.js:58:5
20:29:29.995 |  
20:29:29.995 | - timers.js:434 processImmediate
20:29:29.995 | internal/timers.js:434:9
20:29:29.995 |  
20:29:29.995 |  
20:29:29.995 | error There was an error in your GraphQL query:
20:29:29.996 | The "url" argument must be of type string. Received undefined
20:29:29.996 | 39 \|   uuid
20:29:29.996 | 40 \|   page
20:29:29.996 | 41 \|   codeinjection_foot
20:29:29.996 | 42 \|   codeinjection_head
20:29:29.996 | 43 \|   codeinjection_styles
20:29:29.996 | 44 \|   comment_id
20:29:29.996 | 45 \|   reading_time
20:29:29.997 | 46 \|   childHtmlRehype {
20:29:29.997 | 47 \|     html
20:29:29.997 | 48 \|     htmlAst
20:29:29.997 | > 49 \|     tableOfContents
20:29:29.997 | \|     ^
20:29:29.997 | 50 \|   }
20:29:29.997 | 51 \|   featureImageSharp {
20:29:29.997 | 52 \|     base
20:29:29.997 | 53 \|     publicURL
20:29:29.997 | 54 \|     imageMeta {
20:29:29.998 | 55 \|       width
20:29:29.998 | 56 \|       height
20:29:29.998 | 57 \|     }
20:29:29.998 | 58 \|     childImageSharp {
20:29:29.998 | 59 \|       fluid(maxWidth: 1040) {
20:29:29.998 | File path: /vercel/workpath0/node_modules/gatsby-theme-try-ghost/src/templates/page.js
20:29:29.998 | Url path: /privacy-policy/
20:29:29.998 | Plugin: none
20:29:30.010 |  
20:29:30.010 | Error: TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type st  ring. Received undefined
20:29:30.010 |  
20:29:30.010 | - validators.js:124 validateString
20:29:30.010 | internal/validators.js:124:11
20:29:30.010 |  
20:29:30.011 | - gatsby-node.js:19
20:29:30.011 | [workpath0]/[gatsby-rehype-ghost-links]/gatsby-node.js:19:22
20:29:30.011 |  
20:29:30.011 | - index.js:27 overload
20:29:30.011 | [workpath0]/[unist-util-visit]/index.js:27:12
20:29:30.011 |  
20:29:30.011 | - index.js:56 node (element<a>)
20:29:30.011 | [workpath0]/[unist-util-visit-parents]/index.js:56:27
20:29:30.012 |  
20:29:30.012 | - index.js:67 node (element<p>)
20:29:30.012 | [workpath0]/[unist-util-visit-parents]/index.js:67:75
20:29:30.012 |  
20:29:30.012 | - index.js:67 node (root)
20:29:30.012 | [workpath0]/[unist-util-visit-parents]/index.js:67:75
20:29:30.012 |  
20:29:30.012 | - index.js:29 visitParents
20:29:30.013 | [workpath0]/[unist-util-visit-parents]/index.js:29:26
20:29:30.013 |  
20:29:30.013 | - index.js:22 visit
20:29:30.013 | [workpath0]/[unist-util-visit]/index.js:22:3
20:29:30.013 |  
20:29:30.013 | - gatsby-node.js:16 module.exports
20:29:30.013 | [workpath0]/[gatsby-rehype-ghost-links]/gatsby-node.js:16:3
20:29:30.013 |  
20:29:30.013 | - extend-node-type.js:149
20:29:30.014 | [workpath0]/[gatsby-transformer-rehype]/extend-node-type.js:149:18
20:29:30.014 |  
20:29:30.014 | - extend-node-type.js:16 Function.Promise.each
20:29:30.014 | [workpath0]/[gatsby-transformer-rehype]/extend-node-type.js:16:11
20:29:30.014 |  
20:29:30.014 | - extend-node-type.js:142 processHtmlAst
20:29:30.014 | [workpath0]/[gatsby-transformer-rehype]/extend-node-type.js:142:21
20:29:30.014 |  
20:29:30.014 |  
20:29:30.014 | not finished run page queries - 0.398s
20:29:31.235 | error Command failed with exit code 1.
20:29:31.235 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
20:29:31.243 | Error: Command "yarn run build" exited with 1
20:29:33.840 | Done with "package.json"

**Comment by styxlab** [comment] 2021-04-13 19:28
I suggest that you try to build it locally first, just to see if the same issue pops up.

From the logs it looks like some of your PAGES (privacy page?) in Ghost CMS makes trouble. In order to find the page that causes the error, could you please unpublish your pages first and then publish them one-by-one in order to find the failing content? Are you using anything special in your Ghost CMS (custom css, custome code, etc.?).

For further debugging, I would also need the following infos:

- is the issue also present when you build locally?
- your `env` variables (most likely your content API keys (you can change them later again))
- please send a link to your Github repository from which you are building your site.

**Comment by DevelopingUK** [comment] 2021-04-13 19:46
Thanks, you were right.

Removing the privacy page fixed the issue. My plan is to create a new privacy page, I'm not quite sure why the original one didn't work.

Next, I need to add links in the footer to terms and privacy, I know I can use shadowing and I asked you for help before but I couldn't get it to work.

Also, for the subscribe forms, what do I use? (Mailchimp)?

thanks!!

Once I'm finished with these small edits, let me buy you a coffee.

**Comment by DevelopingUK** [comment] 2021-04-13 20:11
Removing the original privacy policy page, including the content, and generating a new one fixed the problem with that.

I think when it was copied and pasted it included something it shouldn't have.

**Comment by styxlab** [comment] 2021-04-13 21:43
> Next, I need to add links in the footer to terms and privacy, I know I can use shadowing and I asked you for help before but I couldn't get it to work.

Component shadowing is a bit tricky, and you'll find some info on this by searching closed issue. I recommend you to read the [Styling section of the ToC doc](https://www.jamify.org/2020/04/21/adding-a-table-of-contents/#customize-styling) first. Just make sure you get the folder structure right.
 
> Also, for the subscribe forms, what do I use? (Mailchimp)?

You simply need to include the  `gatsby-theme-ghost-members` plugin and setup email in your Ghost CMS (membership section). Ghost uses MailGun as a provider, you can follow their docs.

> Once I'm finished with these small edits, let me buy you a coffee.

Cool, I am a coffee addict. You can use the Github Sponsor button for that.

**Comment by DevelopingUK** [comment] 2021-04-14 07:36
Thanks.

I can't find the original files to shadow.

I'm in vscode and 'SRC/images/' is the only mention of that.

There is no other src file anywhere to be found.

I can't even find the original index.js pages anywhere.

What am I missing here?

**Comment by DevelopingUK** [comment] 2021-04-14 07:54
why is it so difficult to remove the Jamify link in the footer?

Literally, that is the only thing I need to do.

**Comment by styxlab** [comment] 2021-04-14 08:05
> why is it so difficult to remove the Jamify link in the footer?

Shouldn't be difficult, see #259.

**Comment by styxlab** [comment] 2021-04-14 08:07
I am going to close this issue, as the original topic is solved. Please open a new issue, if needed.

**Closed by styxlab** 2021-04-14 08:07 UTC
