### ISSUE TITLE
custom css not being applied using shadowing?

### ISSUE THREAD

**Issue by Buda9** [styxlab/gatsby-theme-try-ghost#256] opened 2021-03-02 17:45 UTC
Dear styxlab,

Thank you for this wonderful repo.

I'm trying to change css using shadowing but it's not being reflected on live site. I'm using path as this: src/gatsby-theme-try-ghost/src/styles/screen.css

E.g. On live site css property "html.casper .site-header-background" has "background: #0a0b0c no-repeat 50%;" but in shadowing files I've set this to be "background: #e60000;"

Would you mind taking a quick look why it's not working? I'd be very grateful 🙏🏻
https://github.com/Buda9/vokabulablog

**Comment by styxlab** [comment] 2021-03-04 08:25
Have a look at the article I wrote about adding and modifying a [Table of Contents](https://www.jamify.org/2020/04/21/adding-a-table-of-contents/) which also explains how to use Gatsby component shadowing.

The problem is your path, you must drop the second `src`. So in your case, the correct path is:

```
src/gatsby-theme-try-ghost/styles/screen.css
```

Please be aware that by shadowing `screen.css` and `global.css` you are opting out of any style updates of the base project. Unless you want a completely different style, it's better to shadow and amend one of the smaller stylesheets, e.g. the `fluid.css` stylesheet and use it to overwrite styles of `screen.css`.

**Comment by styxlab** [comment] 2021-03-08 10:15
Closed as answered.

**Closed by styxlab** 2021-03-08 10:15 UTC
